GET http://localhost:8080/v1/
X-Bare-Host: example.com
X-Bare-Port: 443
X-Bare-Protocol: https:
X-Bare-Path: /
X-Bare-Headers: {"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"}
